### ISSUE TITLE
Extending JScience for NonSI-Labels

### ISSUE THREAD

**Issue by Taspolat** [SENSIDL-PROJECT/SensIDL#2]
JScience binding should be extended further for the support of NonSI-Labels.

**Comment by groenda** [comment]
Include Documentation using markdown on how to extend the known units.

**Comment by groenda** [comment]
Its actually more a JScience converter being aware of more then the SI units and allowing custom extension to handle NonSI Units like Dimensionless or Byte.

**Comment by Taspolat** [comment]
"Dimensionless" now can be used as Unit. Further enhancements for NonSI-labels are still to be done.

**Comment by SvenEckhardt** [comment]
Class is already extended for different byte units, for further extensions the developers will be able to use help system how to achieve that (see #17)
