### ISSUE TITLE
Start discussion of relation to Eclipse Vorto

### ISSUE THREAD

**Issue by groenda** [SENSIDL-PROJECT/SensIDL#20]
Discuss where Vorto and SensIDL overlap or complement each other. The discussion should be made at the [Vorto wiki](https://wiki.eclipse.org/Vorto_/_Meta_Information_Model_/_Discussion_/_SensIDL) . Provide a first draft including a 
- [x] graphical concept and 
- [x] listing of differences and commonalities
- [x] outlook on upcoming protocol support

**Comment by Taspolat** [comment]
Please refer to: 
* http://sensidl-project.github.io/SensIDL/documentation.html 
* https://wiki.eclipse.org/Vorto_/_Meta_Information_Model_/_Discussion_/_SensIDL

**Comment by Taspolat** [comment]
For communication protocol support there is a new issue:  https://github.com/SENSIDL-PROJECT/SensIDL/issues/22
