### ISSUE TITLE
Provide Wizard for Example Projects

### ISSUE THREAD

**Issue by SvenEckhardt** [SENSIDL-PROJECT/SensIDL#38]
Provide a wizard to be found at New > Examples... for the sensidl example projects

**Comment by SvenEckhardt** [comment]
6273664 Adds a Wizard which can be found at New > Examples... for the examples. The newly created project de.fzi.sensidl.examples contains the two example projects which are put in there manually. 
In the future they shouldn't be copied in there but only be referenced.

**Comment by Taspolat** [comment]
The further enhancement of the existing examples project can be done milestone 0.3.

**Comment by SvenEckhardt** [comment]
6918968 makes that enhancement so that the projects are only referenced
