### ISSUE TITLE
Test generators for Qivicon Binding APIs

### ISSUE THREAD

**Issue by Taspolat** [SENSIDL-PROJECT/SensIDL#45]
The generators need to be tested for further Qivicon Bindings to support receiver/gateway side code generation. As reference implementation, the current Qivicon/Galileo demonstrator is to be used. First, it is to be checked how generation conform the current binding is.

**Comment by Taspolat** [comment]
Please mark the code respectively where the generated data structures are needed to be handled in binding code.

**Comment by FabiScheytt** [comment]
Correspondent Commit
https://github.com/SENSIDL-PROJECT/SensIDL/commit/6029cb19cb6587d98e2d5dd1a8930e27c2269bcb
