### ISSUE TITLE
Data adjustment needs additional data type

### ISSUE THREAD

**Issue by nathaliehipp** [SENSIDL-PROJECT/SensIDL#52]
Data adjustment needs additional data type for the target value. 
It makes no sense a linear mapping from a range uint [0; 255] to uint [0;1] (example: emeter.sidl).
When generating the c- and java-file the problem occurs.

**Comment by SvenEckhardt** [comment]
5524601072f7238d039c142cfc027a60524eb274 adds an additional data type after a linear data conversion with intervall. 

Also the Java Generator was is enhanced to fit these changes. For example the `powerFactor `data from the emeter example:
`powerFactor as UINT16 in Dimensionless adjusted by linear mapping [0;255] => [0;1] as FLOAT`
this is generated to two variables: `short powerFactor `and `float powerFactorAdjusted`. When the `getPowerFactor() ` Method is called `powerFactorAdjusted` will be returned. 

The C Generator still needs to be changed.
