### ISSUE TITLE
DataAdjustments need to handle Boolan and String types differently

### ISSUE THREAD

**Issue by Taspolat** [SENSIDL-PROJECT/SensIDL#56]
A simple adjustment needs to be implemented for SensIDL-Datatypes
- [ ] String to Unicode representations
- [ ] Boolean to 0/1

**Comment by ChristophRathfelder** [comment]
Maybe in a first step, we do not need any adjustments for boolean or string types. Resulting in the fact, that data adjustments can only be assigned to numerical data types.

**Comment by SvenEckhardt** [comment]
That's right. 7a292736c3f47cf151c9ace57a643b52c7d4ab1a made also boolean not adjustable, now string and boolean are not adjustable and so there is no need to handle boolean and string adjustments at the moment. This changes are only made in the grammar and not in the meta model.
