### ISSUE TITLE
constant value of NonMeasurementData causes problems in generated java code

### ISSUE THREAD

**Issue by max-peters** [SENSIDL-PROJECT/SensIDL#75]
There are no setters for constant values, but it is possible not to initialise these values.
That causes problems like this.

	private java.lang.Short VOLTAGE = (short) ( - java.lang.Short.MAX_VALUE);

	public java.lang.Short getVoltage() {
		return (short) (VOLTAGE2 + java.lang.Short.MAX_VALUE);
	}
	// no setter for constant value

**Comment by SvenEckhardt** [comment]
A constant NonMeasurementData needs to have a initialised value. The grammar was changed so that a value needs to be set after the keyword 'constant'
