### ISSUE TITLE
In textual Editor UNIT rule overshadows RULE_ID

### ISSUE THREAD

**Issue by SvenEckhardt** [SENSIDL-PROJECT/SensIDL#8]

**Comment by SvenEckhardt** [comment]
Possible Workaround: Change UNIT rule to not allow leading underscores. Then RULE_ID will be recognized by a leading underscore.

**Comment by Taspolat** [comment]
Until we find a concrete solution, the workaround is implemented. Every ID needs to start with an underscore.

**Comment by groenda** [comment]
Is it sufficient if the rules are different? It seems kind of strange that one of them must have an underscore. Only allowing it for one wouldn't have a big effect. Valid UNIT does not start with an underscore anyway.

**Comment by Taspolat** [comment]
Yes, it is sufficient if the rules are different. In that case one will not be overshadowed by the other.
