### ISSUE TITLE
IMappingContext from Vorto cannot be resolved after a fresh update

### ISSUE THREAD

**Issue by Taspolat** [SENSIDL-PROJECT/SensIDL#81]
After updating Vorto to the newest stable, a dependency issue arises for IMappingContext in SensIDLGenerator as an unresolved dependency. 

Version:  _Vorto Toolset All-in-One Bundle (Incubation)	0.4.0.201606070121	org.eclipse.vorto.feature.feature.group	Eclipse.org/Vorto_

Error message: _An internal error occurred during: "Generating Code using SensIDL Generator".
Unresolved compilation problem: 
	The type SensIDLGenerator must implement the inherited abstract method IVortoCodeGenerator.generate(InformationModel, InvocationContext)_

**Comment by Taspolat** [comment]
Seems that IMappingContext is deprecated, at least cannot be found in the newest build.

**Comment by SvenEckhardt** [comment]
6493c11 resolves this
