### ISSUE TITLE
java generator does not create necessary imports for used data sets and utility class

### ISSUE THREAD

**Issue by max-peters** [SENSIDL-PROJECT/SensIDL#84]
/*	
	 * 
	 */
	private TestDataSet2 testDataSet2;

	/**
	 * @param sovalue1
	 *            the sovalue1 to set
	 */
	public void setSovalue1WithDataConversion(java.lang.Byte sovalue1) {
		try {
			final double offset = 2.0;
			final double scalingFactor = 3.0;
			
			this.sovalue1 = (byte) eMeterUtility.linearConversion(sovalue1, scalingFactor, offset);
		} catch (IllegalArgumentException e) {
			//Do something
		}
	}

TestDataSet2 and eMeterUtility dont get imported.

**Comment by max-sch** [comment]
If the code is generated as a plug-in-project the classes will generated in the same package. If the code is generated as simple classes than a package will defined for each class. I would suggest to generate the simple classes in a common package like it's done in the plug-in-project. This requires the user to copy all classes in the same package and no imports are needed anymore.
