### ISSUE TITLE
Datatype with constant attribute does not accept value

### ISSUE THREAD

**Issue by ChristophRathfelder** [SENSIDL-PROJECT/SensIDL#89]
If a datatype is defined with the attribute constant the editor requires a value. Anyhow, the code completion leads to value = STRING, putting any value after the equal symbol is not accepted. Neither wir " nor ' and plain text or numbers.

**Comment by SvenEckhardt** [comment]
The value depends on the dataType of the Data. So for example if the dataType is UINT8 only integer values are valid, i.e. "1" is a valid value, but "String" isn't. 
Values need to be enclosed by `"`

This line is valid: 
`data as UINT8 constant value = "1"`
but this is not a valid value for the dataType:
`data as UINT8 constant value = "String"`

Could you provide the example that doesn't work?
