### ISSUE TITLE
Provide graphical Sirius diagrams for the SensILD language

### ISSUE THREAD

**Issue by Taspolat** [SENSIDL-PROJECT/SensIDL#95]

**Comment by max-peters** [comment]
![sensidl class diagram](https://cloud.githubusercontent.com/assets/15524932/17083347/2288e272-519e-11e6-918e-37cb1f9a6140.jpg)
![datarepresentation class diagram](https://cloud.githubusercontent.com/assets/15524932/17083349/35c09a60-519e-11e6-8653-584203136034.jpg)
