### ISSUE TITLE
Reorganize SensIDL GitHub structure

### ISSUE THREAD

**Issue by joehen** [SENSIDL-PROJECT/SensIDL#97]
Usage of a more streamlined eclipse repo layout for SensIDL. Migrate documentation, examples and demos to separate repos.

**Comment by joehen** [comment]
Proposed new structure for the SensIDL project:
## Top Level Projects

- SensIDL
   - bundles
  - features
  - releng
  - tests
- SensIDL - Vorto Integration
  - bundles
  - features
  - releng
  - tests

- SensIDL - Publications
- SensIDL - Demonstration
- SensIDL - Examples


Open question was whether we want to extract the SensIDL metamodel to a dedicated repository separated from the ui and the code generators. Moreover, we might use separate repos for the different use cases in the demonstration.

**Comment by ChristophRathfelder** [comment]
For me the structure makes sense. I don't see the need to have seperated repositories for the demonstrators as well as the meta-model.
